### ISSUE TITLE
Add description and keywords to GitHub

### ISSUE THREAD

**Issue by Saduras** [i-machine-think/signal#2]
Add a short description to GitHub to inform visitors about the purpose of the project. Further, add relevant keywords. This will help the project to be found with search.

**Comment by lromor** [comment]
@eliabruni we don't have the enough permissions to include the description :(

A possible description could be something like:

_A library built on top of pytorch that provides tools to simplify the development of multi-agent referential games models that aim to research language emergence._

**Comment by eliabruni** [comment]
@lromor I upgraded you to maintain, could you pls check again?

**Comment by lromor** [comment]
Done. Thanks!

**Comment by eliabruni** [comment]
Great, thanks!
